CREATE TABLE "tickers_info" (
	-- Уникальный идентификатор тикера
	"ticker_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- Название компании
	"name" VARCHAR(255),
	-- Символ биржевого тикера
	"ticker" VARCHAR(255) NOT NULL UNIQUE,
	-- Тип ценности
	"item_type" VARCHAR(255),
	-- Экономический сектор
	"sector" VARCHAR(255),
	-- Раздел внутри сектора
	"industry" VARCHAR(255),
	-- Код биржи, на которой торгуются акции
	"exchange_code" VARCHAR(255),
	PRIMARY KEY("ticker_id")
);
COMMENT ON COLUMN tickers_info.ticker_id IS 'Уникальный идентификатор тикера';
COMMENT ON COLUMN tickers_info.name IS 'Название компании';
COMMENT ON COLUMN tickers_info.ticker IS 'Символ биржевого тикера';
COMMENT ON COLUMN tickers_info.item_type IS 'Тип ценности';
COMMENT ON COLUMN tickers_info.sector IS 'Экономический сектор';
COMMENT ON COLUMN tickers_info.industry IS 'Раздел внутри сектора';
COMMENT ON COLUMN tickers_info.exchange_code IS 'Код биржи, на которой торгуются акции';


CREATE TABLE "end_of_day_data" (
	-- Уникальный идентификатор торгов
	"eod_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- Символ биржевого тикера
	"symbol" VARCHAR(255) NOT NULL,
	-- Символ биржи
	"exchange" VARCHAR(255) NOT NULL,
	-- Цена открытия акции на указанную дату
	"open" NUMERIC(12,3) NOT NULL,
	-- Наивысшая цена акции на указанную дату
	"high" NUMERIC(12,3) NOT NULL,
	-- Наименьшая цена акции на указанную дату
	"low" NUMERIC(12,3) NOT NULL,
	-- Цена закрытия акции на указанную дату
	"close" NUMERIC(12,2) NOT NULL,
	-- Количество акций
	"volume" NUMERIC(15,2) NOT NULL,
	-- Скорректированная наивысшая цена акции
	"adj_high" NUMERIC(12,4) NOT NULL,
	-- Скорректированная наименьшая цена акции
	"adj_low" NUMERIC(12,4) NOT NULL,
	-- Скорректированная цена на закрытии 
	"adj_close" NUMERIC(12,4) NOT NULL,
	-- Скорректированная цена на этапе открытия
	"adj_open" NUMERIC(12,2) NOT NULL,
	-- Скорректированное количество акций 
	"adj_volume" NUMERIC(15,2) NOT NULL,
	-- Сколько новых акций было выдано в ходе торгов
	"split_factor" NUMERIC(5,2) NOT NULL,
	-- Дата проведения торгов
	"date" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("eod_id")
);
COMMENT ON COLUMN end_of_day_data.eod_id IS 'Уникальный идентификатор торгов';
COMMENT ON COLUMN end_of_day_data.symbol IS 'Символ биржевого тикера';
COMMENT ON COLUMN end_of_day_data.exchange IS 'Символ биржи';
COMMENT ON COLUMN end_of_day_data.open IS 'Цена открытия акции на указанную дату';
COMMENT ON COLUMN end_of_day_data.high IS 'Наивысшая цена акции на указанную дату';
COMMENT ON COLUMN end_of_day_data.low IS 'Наименьшая цена акции на указанную дату';
COMMENT ON COLUMN end_of_day_data.close IS 'Цена закрытия акции на указанную дату';
COMMENT ON COLUMN end_of_day_data.volume IS 'Количество акций';
COMMENT ON COLUMN end_of_day_data.adj_high IS 'Скорректированная наивысшая цена акции';
COMMENT ON COLUMN end_of_day_data.adj_low IS 'Скорректированная наименьшая цена акции';
COMMENT ON COLUMN end_of_day_data.adj_close IS 'Скорректированная цена на закрытии ';
COMMENT ON COLUMN end_of_day_data.adj_open IS 'Скорректированная цена на этапе открытия';
COMMENT ON COLUMN end_of_day_data.adj_volume IS 'Скорректированное количество акций ';
COMMENT ON COLUMN end_of_day_data.split_factor IS 'Сколько новых акций было выдано в ходе торгов';
COMMENT ON COLUMN end_of_day_data.date IS 'Дата проведения торгов';


CREATE TABLE "exchanges" (
	-- международный код биржи
	"exchange_mic" VARCHAR(255) NOT NULL UNIQUE,
	-- аббревиатура биржи
	"acronym1" VARCHAR(255) NOT NULL UNIQUE,
	-- город
	"city" VARCHAR(255) NOT NULL,
	-- страна биржи
	"country" VARCHAR(255),
	-- сайт биржи
	"website" VARCHAR(255),
	-- код страны
	"alpha2_code" VARCHAR(255),
	-- полное название биржи
	"exchange_name" VARCHAR(255),
	PRIMARY KEY("exchange_mic")
);
COMMENT ON COLUMN exchanges.exchange_mic IS 'международный код биржи';
COMMENT ON COLUMN exchanges.acronym1 IS 'аббревиатура биржи';
COMMENT ON COLUMN exchanges.city IS 'город';
COMMENT ON COLUMN exchanges.country IS 'страна биржи';
COMMENT ON COLUMN exchanges.website IS 'сайт биржи';
COMMENT ON COLUMN exchanges.alpha2_code IS 'код страны';
COMMENT ON COLUMN exchanges.exchange_name IS 'полное название биржи';